/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {

	/**
	 * Test the default constructor and the secondary constructor that loads a
	 * specific test config.
	 */
	@Test 
	public void simpleTest() {

		App app = new App();
		assertNotNull(app);

		app = new App("src/test/resources/simpleConfig.json");
		assertNotNull(app);

	}

}
